### ISSUE TITLE
Request: GNOME Shell login theme

### ISSUE THREAD

**Issue by joshmhanson** [pop-os/theme#4]
The login screen for GNOME Shell still looks very generic. I would suggest also adding a theme for the login screen that matches the Pop theme.

Here is an example of a really well done login theme: https://github.com/godlyranchdressing/United-GNOME/tree/master/extras/login-gnome-shell

**Comment by isantop** [comment]
Part of the problem with theming the login screen is that GDM3 will only pull the system default GNOME Shell theme, and then uses that for the login screen theme. It's possible to install the Pop GNOME Shell theme as the system-default, but this prevents users from using the default Adwaita theme and requires custom-packaging of the `gnome-shell` package. This is likely feasible for the Pop!_OS distro, but not for the basic theme packaging.

_As a note about Debian policies, it's not allowed for one package to modify the files installed by a different package, and attempting to do so will result in the new package not being installable. This is what prevents Pop (or any other theme) from simply including the GNOME Shell theme in its own packaging._
